### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by mrcasual** [MiniCodeMonkey/Vagrant-Laravel-Stack#1]
Hey,

1) Won't work under windows with default `Vagrantfile` since `vagrant-hostmanager` is for *nix only.
2) Your `chef-apache24` repo is misssing (check the `Berksfile`)

Cheers.

**Comment by MiniCodeMonkey** [comment]
Thanks for opening the issue!

1) Sorry, there doesn't seem to be any hosts file managing plugins for Windows yet that are compatible with Vagrant 1.3x - You should be able to just comment out / remove this section

2) I had a typo in the repository name, this was just fixed about an half hour ago https://github.com/MiniCodeMonkey/Vagrant-Laravel-Stack/commit/ed2d2251c8b676b57c403802c945b72a18fe9f85

**Comment by MiniCodeMonkey** [comment]
Looking further into Vagrant Hostmanager, it looks like it should be fully Windows compatible. https://github.com/smdahlen/vagrant-hostmanager/blob/master/lib/vagrant-hostmanager/hosts_file.rb - Can you please confirm?
