### ISSUE TITLE
Forbidden When Trying To Access Beanstalk Console

### ISSUE THREAD

**Issue by allistera** [MiniCodeMonkey/Vagrant-Laravel-Stack#12]
When I try and access the Beanstalk Console I get:

Forbidden

You don't have permission to access /beanstalk/ on this server.

**Comment by MiniCodeMonkey** [comment]
This should have been resolved now https://github.com/MiniCodeMonkey/chef-beanstalk_console/pull/1

**Comment by allistera** [comment]
Managed to get it working by going to beanstalk/public/
