### ISSUE TITLE
Fatal Errors

### ISSUE THREAD

**Issue by michaelgrossklos** [MiniCodeMonkey/Vagrant-Laravel-Stack#13]
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
- The 'hostmanager' provisioner could not be found.

Vagrant:
- Unknown configuration section 'berkshelf'.
- Unknown configuration section 'hostmanager'.

**Comment by MiniCodeMonkey** [comment]
Please make sure that you have the `hostmanager` and `berkshelf` plugins installed.

```
vagrant plugin install vagrant-berkshelf
vagrant plugin install vagrant-hostmanager
```

**Comment by michaelgrossklos** [comment]
OK, thx for help! This was the problem
