### ISSUE TITLE
could not find recipe default for cookbook mysql

### ISSUE THREAD

**Issue by chrischnweiss** [MiniCodeMonkey/Vagrant-Laravel-Stack#19]
Hi folks,
today I got a new error by trying to provision a new machine. It seems to be there is a problem with the cookbook for mysql.

Error i got:

Recipe Compile Error
Chef::Exceptions::RecipeNotFound
could not find recipe default for cookbook mysql

Can anyone help please?

**Comment by dionsnoeijen** [comment]
I have the same issue, I have been trying to fix this for a couple of hours now without success. If anyone know's what's going on I would also really like to hear about this! Thanks :+1:

**Comment by MiniCodeMonkey** [comment]
Chef updated their MySQL cookbook  to no longer support the `mysql` recipe.
This was fixed here.

https://github.com/MiniCodeMonkey/chef-laravel/pull/1
