### ISSUE TITLE
failed to open stream: Permission denied

### ISSUE THREAD

**Issue by HellPat** [MiniCodeMonkey/Vagrant-Laravel-Stack#2]
`file_put_contents(vendor/composer/installed.json): failed to open stream: Permission denied`

On composer update i get this error. Do i have to set permissions for vendor directory?
How about app/storage? Could this be done automatically?

**Comment by MiniCodeMonkey** [comment]
Did you run `composer install` or `composer update` from your local machine or within the virtual machine? (e.g. you did `vagrant ssh` first)

**Comment by HellPat** [comment]
I did run composer install from within the vm. Destroyed the vm.
Again did a vagrant up.

Then

```
vagrant ssh
cd /var/www/myproject
composer update
```

**Comment by MiniCodeMonkey** [comment]
Hmm, I was a little bit too hesitant with that fix (reverted it again).

`/var/www/myproject` is owned by the `vagrant` user per default (which is the one you are logging in with, when using `vagrant ssh`). I just verified the issue here, and I can't seem to get the same error message. It doesn't make sense that `vagrant` doesn't have write permission to that full folder :)

Can you please verify that you are logged in as `vagrant` (e.g. by running `whoami`), and then reply with the full permissions of the project folder on the VM by running `ls -al /var/www/myproject`.

**Comment by HellPat** [comment]
Funny... did the same fix as you did but ran into hassle.
I'll be back with feedback in a few minutes.

**Comment by HellPat** [comment]
mhh...

`whoami => vagrant`

```
drwxr-xr-x 1 vagrant vagrant   680 Oct  1 17:01 .
drwxr-xr-x 4 root    root     4096 Oct  1 16:27 ..
drwxr-xr-x 1 vagrant vagrant   510 Oct  1 14:00 app
-rwxr-xr-x 1 vagrant vagrant  2424 Oct  1 12:26 artisan
-rw-r--r-- 1 vagrant vagrant   716 Oct  1 12:39 Berksfile
-rw-r--r-- 1 vagrant vagrant  2459 Oct  1 16:08 Berksfile.lock
drwxr-xr-x 1 vagrant vagrant   170 Oct  1 12:26 bootstrap
-rw-r--r-- 1 vagrant vagrant   787 Oct  1 13:59 composer.json
-rw-r--r-- 1 vagrant vagrant 62491 Oct  1 17:01 composer.lock
-rw-r--r-- 1 vagrant vagrant   145 Oct  1 12:26 CONTRIBUTING.md
drwxr-xr-x 1 vagrant vagrant   510 Oct  1 14:40 .git
-rw-r--r-- 1 vagrant vagrant    11 Oct  1 12:26 .gitattributes
-rw-r--r-- 1 vagrant vagrant    93 Oct  1 12:38 .gitignore
-rw-r--r-- 1 vagrant vagrant   566 Oct  1 12:26 phpunit.xml
drwxr-xr-x 1 vagrant vagrant   272 Oct  1 14:02 public
-rw-r--r-- 1 vagrant vagrant  1795 Oct  1 12:26 readme.md
-rw-r--r-- 1 vagrant vagrant   519 Oct  1 12:26 server.php
drwxr-xr-x 1 vagrant vagrant   102 Oct  1 12:41 .vagrant
-rw-r--r-- 1 vagrant vagrant  5845 Oct  1 15:39 Vagrantfile
drwxr-xr-x 1 vagrant vagrant   612 Oct  1 17:01 vendor
```

After this reboot composer update works. Leaving me with the permission problem "file_put_contents(/var/www/workers/app/storage/meta/services.json): failed to open stream: Permission denied"

if i `chmod -R 777 app/storage`it works for 1 request and then the newly create session isn't writable.

I get `SessionHandler::read(): open(/var/www/workers/app/storage/sessions/sess_rh1huncfa3i6036ae3denvf105, O_RDWR) failed: Permission denied (13)` now.

**Comment by HellPat** [comment]
It's not really a fix, but this way it works for me.

``` ruby
# Set share folder
config.vm.synced_folder "./" , "/var/www/" + project_name + "/", :mount_options => ["dmode=777","fmode=666"]
```

**Comment by MiniCodeMonkey** [comment]
I've decided to apply this solution to `master` as the security implications vs. convenience factor isn't really a concern on a development environment like this.

**Comment by HellPat** [comment]
This is my opinion, too. Thanks.

**Comment by whoisandy** [comment]
Change the owner of the vagrant folder to www-data. Works for me without even tweaking the Vagrantfile.

I just did a chown -R www-data:www-data /vagrant

**Comment by deemyboy** [comment]
what id you don't have a www-data user

**Comment by Imekhan** [comment]
just  change ownership and it will work, like: # sudo chown -R yourusername:yourusername directory_name

**Comment by askawam** [comment]
just do:
php artisan cache:clear

**Comment by KyawNaingTun** [comment]
Thanks @exiler  (y)

**Comment by YutangShi** [comment]
Thanks @exiler , But, What is the reason?

**Comment by ripu123** [comment]
i have same error file_put_contents(/storagereport.pdf): failed to open stream: Permission denied..i have done the file permission also but error still showing..

**Comment by HellPat** [comment]
You are writing to the root directory of the box.
Try **DIR**.'/storagereport.pdf'

**Comment by bretto36** [comment]
Just for anyone else who gets this error on a live environment. You might need to put sudo in front of the command

eg sudo composer install

**Comment by omitobi** [comment]
@bretto36 Its generally bad to add sudo when install a package via composer because there may be malicious package(s) you're allowing to be installed via `sudo`
