### ISSUE TITLE
The 'hostmanager' provisioner could not be found.

### ISSUE THREAD

**Issue by donaldallen** [MiniCodeMonkey/Vagrant-Laravel-Stack#3]
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
- The 'hostmanager' provisioner could not be found.

Vagrant:
- Unknown configuration section 'berkshelf'.
- Unknown configuration section 'hostmanager'.

Followed directions to a tee. Latest Vagrant, on OSX 10.8.5. Latest composer as well.

**Comment by MiniCodeMonkey** [comment]
Make sure that you have installed all the required software, namely:
- [Berkshelf](http://berkshelf.com)
  - `gem install berkshelf`
- [vagrant-berkshelf](https://github.com/riotgames/vagrant-berkshelf)
  - `vagrant plugin install vagrant-berkshelf`
- [vagrant-hostmanager](https://github.com/smdahlen/vagrant-hostmanager)
  - `vagrant plugin install vagrant-hostmanager`

**Comment by donaldallen** [comment]
Thanks! vagrant up now gets to this point:

`[Berkshelf] Failed to download 'postgresql' from git: 'git://github.com/phlipper/chef-postgresql' with branch: 'master'
Berkshelf::CookbookNotFound: Cookbook 'postgresql' not found in any of the default locations`

Seems like any git:// protocols aren't working. Hmm.

**Comment by MiniCodeMonkey** [comment]
Hmm, there doesn't seem to be any problems with the repository URL. It might be related to the [downtime that GitHub just had](https://status.github.com/messages). I would try again in an hour or so.

I've had buggy behavior like this from Berkshelf before, it usually helps to clear the Berkshelf project data `rm -rf ~/.berkshelf/projectname` and `Berkshelf.lock` in your project directory or just try again.

**Comment by allistera** [comment]
Also experiencing failed to download when running vagrant up, cloning the repo from the command line works, so link is working okay.

**Comment by lumpygator** [comment]
I had the same issue with Berkshelf not being able to download cookbooks using git. 

It appears that it is related to a Vagrant 1.3.3/Berkshelf 1.3.3 issue.  The solution was to downgrade to Vagrant 1.3.2 until a fix is in place.

See https://github.com/RiotGames/vagrant-berkshelf/issues/93 for more info.

**Comment by mmannerm** [comment]
Vagrant 1.3.4 was released and fixes the issue.

**Comment by MiniCodeMonkey** [comment]
Awesome crowd sourcing guys! I had this issue at some point too when developing the stack, glad that it has been resolved.

I'm going the close the issue.

**Solution:** Update to the newest version of Vagrant.
