### ISSUE TITLE
Install PHPUnit

### ISSUE THREAD

**Issue by HellPat** [MiniCodeMonkey/Vagrant-Laravel-Stack#4]
Would be nice if PHPUnit would be installed

**Comment by MiniCodeMonkey** [comment]
I usually install phpunit via composer on a per-project basis. Not sure if it should be installed per default in the VM.

I'll leave this issue open for a week or two to see if anyone else have interest in having phpunit installing per default.

**Comment by laurentvd** [comment]
I agree with psren. It should be installed and configured in the PATH by default.

**Comment by laurentvd** [comment]
I created a pull request https://github.com/MiniCodeMonkey/Vagrant-Laravel-Stack/pull/8

**Comment by MiniCodeMonkey** [comment]
Thanks! It's merged.
