### ISSUE TITLE
project directory /var/www/projectname doesn' t exist on VM

### ISSUE THREAD

**Issue by dragouf** [MiniCodeMonkey/Vagrant-Laravel-Stack#5]
I' m on Macos Mountain lion.

I renamed the projectname variable.

I noticed that I couldn' t reach project name.local and then after I 

vagrant ssh

I noticed that there was no project directory.

Do you have any idea ?

P.S : thanks for this little vagrant script

**Comment by MiniCodeMonkey** [comment]
Hi,

Make sure to run `vagrant reload` after changing the `projectname` variable so the synced folder names etc. can be configured again for the virtual machine.

Let me know if that worked for you.
