### ISSUE TITLE
laravel permissions exception

### ISSUE THREAD

**Issue by mcallan83** [MiniCodeMonkey/Vagrant-Laravel-Stack#7]
I am a Laravel exception right after the initial boot:

SessionHandler::read(): open(/var/www/projectname/app/storage/sessions/sess_m0334vpbtieepvvnv4l6nvqd16, O_RDWR) failed: Permission denied (13)

Also, going to projectname.local/benstalk is giving me a Forbidden error. Any ideas?

**Comment by dgreda** [comment]
Hey, same here, I'm getting a Forbidden error on projectname.local/beanstalk. Can you guys sort it out?

**Comment by MiniCodeMonkey** [comment]
Make sure to give the webserver write permission to the app/storage directory

e.g. `chmod -R 777 app/storage`

@dgreda:
This should have been resolved now: https://github.com/MiniCodeMonkey/chef-beanstalk_console/pull/1
